name: Deploy Backend Docker Image

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGISTRY_LOCATION: ${{ secrets.GCP_REGISTRY_LOCATION }}
  REGISTRY_NAME: ${{ secrets.GCP_REGISTRY_NAME }}
  IMAGE_NAME: backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker to use gcloud as credential helper
      run: |
        gcloud auth configure-docker ${{ env.REGISTRY_LOCATION }}-docker.pkg.dev

    - name: Get short SHA
      id: sha
      run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: |
        cd backend
        docker build \
          --tag ${{ env.REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.sha.outputs.SHORT_SHA }} \
          --tag ${{ env.REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest \
          .

    - name: Push Docker image
      run: |
        docker push ${{ env.REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.sha.outputs.SHORT_SHA }}
        docker push ${{ env.REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:latest

    - name: Deploy to Cloud Run
      id: deploy
      run: |
        gcloud run deploy backend-api \
          --image ${{ env.REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.sha.outputs.SHORT_SHA }} \
          --platform managed \
          --region ${{ env.REGISTRY_LOCATION }} \
          --allow-unauthenticated \
          --port 8000 \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 10 \
          --set-env-vars="ENVIRONMENT=production,DATABASE_URL=${{ secrets.DATABASE_URL }}" \
          --set-secrets="DB_PASSWORD=db-password:latest"

    - name: Show deployment URL
      run: |
        echo "Backend deployed to: $(gcloud run services describe backend-api --region=${{ env.REGISTRY_LOCATION }} --format='value(status.url)')"

    - name: Run health check
      run: |
        BACKEND_URL=$(gcloud run services describe backend-api --region=${{ env.REGISTRY_LOCATION }} --format='value(status.url)')
        sleep 30  # Wait for service to be ready
        curl -f $BACKEND_URL/health || exit 1
        echo "✅ Backend health check passed"

    - name: Comment deployment info on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const deploymentUrl = `$(gcloud run services describe backend-api --region=${{ env.REGISTRY_LOCATION }} --format='value(status.url)')`;
          const comment = `🚀 **Backend Deployment**
          
          **Docker Image:** \`${{ env.REGISTRY_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.sha.outputs.SHORT_SHA }}\`
          **API URL:** ${deploymentUrl}
          **Health Check:** ${deploymentUrl}/health
          **Commit:** ${context.sha.slice(0, 8)}
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
